### ISSUE TITLE
Only joining and integration reports error

### ISSUE THREAD

**Issue by jhonny001** [jas-williams/CubeCell-Helium-Mapper#2]
Hi Jas, I uploaded to the new version of the Heltec CubeCell Helium mapper and my mapper stopped working.

It is always trying to Join even after receiving a request accept message.

Also the integration status shows error.

I followed the Readme guide and changed the function to the one you provide.

Any ideas why is this happening? I heard the same issue reported by other users after the update...

Cheers.

**Comment by jas-williams** [comment]
Make sure you have the correct Device ID’s etc in the firmware you uploaded
